---
#Description: This playbook creates VM in public cloud using ICF with given OIDs
#
#Input variables
#
# ICF_IP -- ICF IP
# ICF_username -- ICF username
# ICF_password -- ICF password
# catalog_oid -- catalog oid
# vdc_oid -- vdc_oid
# network_oid -- nework_oid
#
####
#Provision some instances:
- hosts: localhost
  connection: local

#this file should be writtable by ansible user awx
  vars_files:
  - /var/lib/awx/projects/cecs-ansible/all_variables

  vars:
    url_token: /token
    url_groups: /user-groups
    url_instance: /instances
    url_logout: /logout
    create_body: " {\"username\":\"{{ICF_username}}\", \"password\":\"{{ICF_password}}\"}"

  tasks:

    - name: HERE Launch ICF instances -- Get token
      uri:
        url: "http://{{ICF_IP}}/icfb/v1{{url_token}}"
        HEADER_Content-Type: "application/json"
        body: "{{create_body}}"
        method: POST
        return_content: yes
      register: result

    - name: HERE Launch ICF instance -- post instance
      uri:
        url: "http://{{ICF_IP}}/icfb/v1{{url_instance}}"
        HEADER_Content-Type: "application/json"
        HEADER_x_icfb_token: "{{result.x_icfb_token}}"
        HEADER_Cookie: "{{result.set_cookie}}"
        method: POST
        body: "{\"vdc_oid\":\"{{vdc_oid}}\",
                \"catalog_oid\":\"{{catalog_oid}}\",
                \"nic_configurations\":[{\"nic_index\":1,\"is_dhcp\":false,\"network_oid\":\"{{network_oid}}\"}]}"
        status_code: 202

    - name: Launch ICF instances -- Logout
      uri:
        url: "http://{{ICF_IP}}/icfb/v1{{url_logout}}"
        HEADER_Content-Type: "application/json"
        HEADER_x_icfb_token: "{{result.x_icfb_token}}"
        HEADER_Cookie: "{{result.set_cookie}}"
        method: POST
